version: "3"

services:
    api:
        # build our custom image
        build: .
        ports:
            - "8000:8000"
#         env_file:
#             - ./.env
        volumes:
            # to automatically sync the two folder in 'ro' - read-only - regime (so that container cannot change files)
            - .:/usr/src/app:ro
        command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
        environment:
            # database hostname is taken from service name below
            - DATABASE_HOSTNAME=postgres
            - DATABASE_PORT=5432
            - DATABASE_USERNAME=postgres3
            - DATABASE_PASSWORD=password123
            - DATABASE_NAME=blogposts
            - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
            - ALGORITHM=HS256
            - ACCESS_TOKEN_EXPIRE_MINUTES=30
        depends_on:
            - postgres

    postgres:
        # use pre-build default postgres image
        image: postgres
        environment:
            - POSTGRES_USER=postgres3
            - POSTGRES_PASSWORD=password123
            - POSTGRES_DB=fastapi-playground
        volumes:
            # indicate the directory inside a container which should persist on our local machine
            - postgres-db:/var/lib/postgresql/data

volumes:
    # define named volume
    postgres-db: